### ISSUE TITLE
Do not throw error when problem proved infeasible in presolve

### ISSUE THREAD

**Issue by ischmidt20** [d-krupke/CP-SAT-Log-Analyzer#12]
Basically the title. If a problem is found infeasible in presolve then the app won't accept the log, presumably because a lot of sections are missing.

LOVE the app by the way!

**Comment by d-krupke** [comment]
Such a log is probably not worth analyzing, but it should not crash the app. I will fix it. Do you by any chance have a log at hand so I can double-check that I fixed the right issue?

PS: There are some further improvements to the app planed. I just need to find the time :)

**Comment by ischmidt20** [comment]
Here are a couple of examples. You're right that there would not be useful analysis, but just the ability for the app to show without crashing that the problem was shown infeasible would be good.

Looking forward to it, the app has been a tremendous help to my work!
[Uploading log_2024-10-25-17-44-23.txt…]()

**Comment by d-krupke** [comment]
Thanks, I will try to fix it later this week and create test cases based on these logs!

**Comment by d-krupke** [comment]
Should be fixed now! :)

**Comment by ischmidt20** [comment]
Can confirm that this works, thanks!
